Repository googleapis/python-functions, pull requests merged in 2020-12, with the labels that each got.

#24 docs: fix link to documentation
  README.rst
Labels: api: cloudfunctions, cla: yes

#25 chore: add pre-commit hook
  .pre-commit-config.yaml
  CONTRIBUTING.rst
  docs/conf.py
  noxfile.py
  synth.metadata
Labels: api: cloudfunctions, cla: yes, context: full

#26 fix: remove client recv msg limit and add enums to `types/__init__.py`
  google/cloud/functions_v1/services/cloud_functions_service/transports/__init__.py
  google/cloud/functions_v1/services/cloud_functions_service/transports/grpc.py
  google/cloud/functions_v1/services/cloud_functions_service/transports/grpc_asyncio.py
  google/cloud/functions_v1/types/__init__.py
  synth.metadata
  tests/unit/gapic/functions_v1/test_cloud_functions_service.py
Labels: api: cloudfunctions, cla: yes, context: full

#27 chore(deps): update precommit hook pre-commit/pre-commit-hooks to v3.4.0
  .pre-commit-config.yaml
  synth.metadata
Labels: api: cloudfunctions, automerge, cla: yes, context: full

#29 chore: exclude `.nox` from linting; document supported python versions
  .flake8
  CONTRIBUTING.rst
  synth.metadata
Labels: api: cloudfunctions, cla: yes, context: full
