Repository googleapis/python-functions, pull requests merged in 2021-04, with the labels that each got.

#42 fix: use correct default retry and timeout
  .coveragerc
  .gitignore
  .kokoro/build.sh
  .kokoro/samples/python3.6/periodic-head.cfg
  .kokoro/samples/python3.7/periodic-head.cfg
  .kokoro/samples/python3.8/periodic-head.cfg
  .kokoro/test-samples-against-head.sh
  .kokoro/test-samples-impl.sh
  .kokoro/test-samples.sh
  .pre-commit-config.yaml
  docs/functions_v1/cloud_functions_service.rst
  docs/functions_v1/services.rst
  docs/functions_v1/types.rst
  functions-v1-py.tar.gz
  google/cloud/functions_v1/services/cloud_functions_service/async_client.py
  google/cloud/functions_v1/services/cloud_functions_service/client.py
  google/cloud/functions_v1/services/cloud_functions_service/pagers.py
  google/cloud/functions_v1/services/cloud_functions_service/transports/base.py
  google/cloud/functions_v1/services/cloud_functions_service/transports/grpc.py
  google/cloud/functions_v1/services/cloud_functions_service/transports/grpc_asyncio.py
  google/cloud/functions_v1/types/__init__.py
  google/cloud/functions_v1/types/functions.py
  google/cloud/functions_v1/types/operations.py
  noxfile.py
  renovate.json
  setup.py
  synth.metadata
  synth.py
  testing/constraints-3.10.txt
  testing/constraints-3.11.txt
  testing/constraints-3.6.txt
  testing/constraints-3.7.txt
  testing/constraints-3.8.txt
  testing/constraints-3.9.txt
  tests/unit/gapic/functions_v1/test_cloud_functions_service.py
Labels: api: cloudfunctions, cla: yes, context: partial

#44 chore: start tracking obsolete files
  synth.metadata
Labels: api: cloudfunctions, cla: yes, context: full

#46 chore: Add license headers for python config files
  .pre-commit-config.yaml
  docs/conf.py
  synth.metadata
Labels: api: cloudfunctions, automerge, cla: yes, context: full

#48 chore: track generated files
  functions-v1-py.tar.gz
  synth.metadata
Labels: api: cloudfunctions, cla: yes, context: none

#47 chore: add constraints file check for python samples
  .github/header-checker-lint.yml
  renovate.json
  synth.metadata
Labels: api: cloudfunctions, automerge, cla: yes, context: full, samples

#51 chore: prevent normalization of semver versioning
  setup.py
Labels: api: cloudfunctions, cla: yes

#54 chore(revert): revert preventing normalization
  setup.py
Labels: api: cloudfunctions, cla: yes
